language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAJSDTIJXHKC2ZTT3Q"
  secret_access_key: "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"
  secure: "mlrAHtFpnDSBv0egHGTf8vyn9UH86SQLmMdXZgXC"
  region: "us-east-1"  
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elasticbeanstalk-us-east-1-882371129764"
  on:
    branch: master
