branch-defaults:
  master:
    environment: elastic-beanstalk-tutorial
    group_suffix: null
global:
  CodeCommit: n
  application_name: elastic-beanstalk-tutorial
  branch: master
  default_ec2_keyname: null
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  profile: eb-cli
  sc: git
 